### ISSUE TITLE
Providing messages from kafka topic to NATS subject

### ISSUE THREAD

**Issue by sizovilya** [nats-io/nats-kafka#12]
Hello guys.
I have kafka as a central event bus in my system. Near future i will implement some functionality depends on NATS. I should to repeat some messages from kafka to NATS, but not whole topic. I need to select some messages depends on string which consists in my message value (for example it can be done using regex). Is it possible to use nats-kafka lib for this purposes?

**Example:**
I have messages in kafka with values:
`{
   "event":"userCreated",
   "version":1,
   "data":{
      "targetId":"5e9f11bae0b5c5dc94a6c070"
   }
}`

`{
   "event":"userDeleted",
   "version":1,
   "data":{
      "targetId":"5e9f11bae0b5c5dc94a6c070"
   }
}`

`{
   "event":"userChanged",
   "version":1,
   "data":{
      "targetId":"5e9f11bae0b5c5dc94a6c070"
   }
}`

But i want to provide to NATS only one type of messages, with **"event":"userDeleted"**.

**Comment by ColinSullivan1** [comment]
Content based routing is not supported, although this is something we'll look into.  To solve a use case like this you could run through a proxy NATS process to filter messages, although core NATS is lightweight and performant enough that the simplest solution could be to just drop messages at consuming application.

Something similar came up in the NATS JMS bridge.  Perhaps we could offer a NATS enabled callout that could send messages to a sidecar for data enrichment and filtering.

**Comment by sizovilya** [comment]
@ColinSullivan1 Thanks for the info. I have implemented my own solution. We can close issue.

**Comment by pauldemarco** [comment]
I'm running into the same need, can you describe a bit on your solution @sizovilya ?
