### ISSUE TITLE
AVRO Support

### ISSUE THREAD

**Issue by danhawkins** [nats-io/nats-kafka#13]
Is there any support for avro encoding / decoding via schema registry at the moment, I couldn't see anything in the configs.

**Comment by robertmircea** [comment]
I would like to see that too.

**Comment by ColinSullivan1** [comment]
This is certainly something we can look into.

**Comment by drnushooz** [comment]
@ColinSullivan1 I can implement this as it is something we are interested in this too. I have worked with Confluent Schema Registry and I can add support it.
