### ISSUE TITLE
NATS to Kafka Bridge Does Not Support SASL+TLS

### ISSUE THREAD

**Issue by jlmorton** [nats-io/nats-kafka#29]
Hi,

I believe this is related to https://github.com/nats-io/nats-kafka/issues/26.  Using a NATSToKafka bridge, I've been unable to connect to a Kafka broker which uses both SASL and TLS.  The current code in `producer.go:52` looks like:

	if cc.SASL.User != "" {
		sc.Net.SASL.Enable = true
		sc.Net.SASL.Handshake = true
		sc.Net.SASL.Mechanism = sarama.SASLTypePlaintext
		sc.Net.SASL.User = cc.SASL.User
		sc.Net.SASL.Password = cc.SASL.Password

		if cc.SASL.InsecureSkipVerify {
			sc.Net.TLS.Enable = true
			sc.Net.TLS.Config = &tls.Config{
				InsecureSkipVerify: cc.SASL.InsecureSkipVerify,
			}
		}
	} else if tlsC, err := cc.TLS.MakeTLSConfig(); err == nil {
		sc.Net.TLS.Enable = (tlsC != nil)
		sc.Net.TLS.Config = tlsC
	}

It appears TLS only gets enabled if SASL is not specified, or if the InsecureSkipVerify flag is set.  If I set InsecureSkipVerify, things work just fine, but without it, TLS is not enabled.

Is there any reason we wouldn't want to move the else-if block to its own check?  Running locally, my issues are resolved if I re-arrange this to:

	if cc.SASL.User != "" {
		sc.Net.SASL.Enable = true
		sc.Net.SASL.Handshake = true
		sc.Net.SASL.Mechanism = sarama.SASLTypePlaintext
		sc.Net.SASL.User = cc.SASL.User
		sc.Net.SASL.Password = cc.SASL.Password

		if cc.SASL.InsecureSkipVerify {
			sc.Net.TLS.Enable = true
			sc.Net.TLS.Config = &tls.Config{
				InsecureSkipVerify: cc.SASL.InsecureSkipVerify,
			}
		}
	}

	if tlsC, err := cc.TLS.MakeTLSConfig(); err == nil {
		sc.Net.TLS.Enable = tlsC != nil
	}

Thanks!

**Comment by variadico** [comment]
Awesome! If `make test` passes for you locally, then maybe you could consider opening a PR to get this fix merged faster. 
🏃🏾 💨 

Either way, thanks for putting this on our radar. 👍🏾

**Comment by variadico** [comment]
What's your config look like?

**Comment by jlmorton** [comment]
@variadico Sorry, I did try to run tests, but I actually couldn't get a couple to pass with my changes stashed.  Hoping to get time to look into that further.

My config currently looks like:

    ReconnectInterval: 5000,
    ConnectTimeout: 5000,
    
    nats: {
        Servers: ["localhost:4222"],
        ConnectTimeout: 5000,
        MaxReconnects: 5,
        ReconnectWait: 5000,
    }
    
    logging: {
        time: true,
        debug: true,
        trace: true,
        colors: true,
        pid: false,
    }
    
    connect: [
        {
            Type: "NATSToKafka",
            Brokers: ["foo.bar.xyz:9092"]
            Id: "bridge",
            Topic: "foo",
            Subject: "foo.bar.*.*",
            QueueName: "bridge",
            KeyType: "subjectre",
            KeyValue: "foo.bar.baz.(.*)"
            tls: {
                Root: "serverca.pem",
                Cert: "bridge.pem",
                Key: "bridge.key"
            },
            Sasl: {
                User: "XXX",
                Password: "ZZZ",
            },
        },
    ],

**Comment by variadico** [comment]
No worries, thanks for the config. It helped figuring out what we want to do. 

Also, looks like I did get some time to look into this a bit more. I have a work in progress branch here: https://github.com/nats-io/nats-kafka/pull/30

If you get a chance, it would be helpful if you could try it out to see if it resolves your issue. Juuust to make sure.
```
git clone git@github.com:nats-io/nats-kafka.git
cd nats-kafka
git checkout sasl-tls
make build
./nats-kafka -c your.conf
```

**Comment by jlmorton** [comment]
Just gave it a shot, and it all worked great!  Thanks for the fix!

**Comment by variadico** [comment]
Awesome, thanks for helping! We'll get this shipped out soon!
