### ISSUE TITLE
Feature Request:  Graceful Shutdown

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats-kafka#36]
Allow for a graceful shutdown minimizing message loss.

Some suggestions:
* Implement a signal handler to shutdown gracefully.  This may be important in k8s.  See [nats-surveyor](https://github.com/nats-io/nats-surveyor/blob/1721785f5a786f6d21ac6279cbf139d8a772f188/main.go#L76).
* On the NATS side use `Conn.Drain()` when exiting.
* Investigate the Kafka Consumer side - check if there is a way to unsubscribe and process what is buffered.

**Comment by variadico** [comment]
The following are done, closing.

- [x] Implement a signal handler to shutdown gracefully
- [x] Add `Conn.Drain()`
- [x] The underlying library already handles [producer graceful shutdown](https://github.com/Shopify/sarama/issues/241)
